version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      # change for more security
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGO
    volumes:
      # in production, use a volume type, uncomment sources
      - type: tmpfs
        # source: mongo-data
        target: /data/db
      - type: tmpfs
        # source: mongo-config
        target: /data/configdb

  mongo-seed:
    build: ./data
    environment:
      MONGODB_URI: mongodb://root:root@mongo:27017/cinema
    networks:
      - MONGO
    depends_on:
      - mongo
      
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - MONGO
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: ./wait-for.sh
        target: /wait-for.sh
    entrypoint:
      # Wait-for script
      - /bin/sh
      - /wait-for.sh
      - mongo:27017
      - --
      - tini
      - --
      - /docker-entrypoint.sh

  cinema-api:  
    build: ./backend  
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8080:8080"  
    environment:
      - MONGODB_URI=mongodb://root:root@mongo:27017
      - MONGODB_NAME=cinema
      - PORT=8080
      - FRONTEND_URI=http://localhost:5000
    networks:
      - MONGO

  cinema-frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - cinema-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - VITE_API_URI=http://localhost:8080/api
    networks:
      - MONGO

networks:
  MONGO:
    name: MONGO

#  for production use (volume type volumes in mongo service), uncomment the following volumes 
# volumes:
#   mongo-data:
#     name: mongo-data
#   mongo-config:
#     name: mongo-config

  


