version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: cw_mongo
    environment:
      # change for more safety
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGO
    volumes:
      - type: tmpfs
        target: /data/db
      - type: tmpfs
        target: /data/configdb

  mongo-seed:
    build: ./data
    environment:
      MONGODB_URI: mongodb://root:root@mongo:27017/cinema
    networks:
      - MONGO
    depends_on:
      - mongo
      
  mongo-express:
    image: mongo-express:latest
    container_name: cw_mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - MONGO
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: ./wait-for.sh
        target: /wait-for.sh
    entrypoint:
      # Wait-for script
      - /bin/sh
      - /wait-for.sh
      - mongo:27017
      - --
      - tini
      - --
      - /docker-entrypoint.sh

  cinema-api:  
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: cw-api
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8080:8080"  
    environment:
      - MONGODB_URI=mongodb://root:root@mongo:27017
      - MONGODB_NAME=cinema
      - PORT=8080
      - JWT_SECRET=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    networks:
      - MONGO
    volumes:
      - ./backend/:/app

  cinema-frontend:
    build: ./frontend
    container_name: cw-frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - cinema-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - VITE_API_URI=http://localhost:8080/api
    networks:
      - MONGO

networks:
  MONGO:
    name: MONGO

  


